### ISSUE TITLE
[Bug]: Falling Out of the World After Generating a New World

### ISSUE THREAD

**Issue by smellyjoe** [TheButterbrotMan/Deathdusk#118]
### What happened?

When I generate a new world under the Deathdusk modpack, I found myself falling through the world terrain and dying in the void as a result. Although I keep my stuff the first time, when I update the modpack and log back into my world, I also fall through the blocks below me and die in the void, losing all of my items in the process. I also found out that the bug occurs when I load up a survival world; I don't fall through the world while starting a creative world. Please let me know if there are any fixes I can do on my end. 
Thanks.

### Version

2.0.10

**Comment by TheButterbrotMan** [comment]
I think it's a problem with MCA, could you remove MCA and confirm this?

**Comment by smellyjoe** [comment]
I will do so and will let you know about any changes.

**Comment by TheButterbrotMan** [comment]
If that dont work, change the string "launchIntoDestiny": to false.

**Comment by smellyjoe** [comment]
Oddly, when I disable/remove mca from the modpack, Minecraft suddenly closes after starting and does not leave an error code or a crash report. When looking into the console, I received this message: 
`17:55:22.005
[17:55:22] [Render thread/INFO]: Aux slot 4 created
17:55:22.010
[17:55:22] [Render thread/INFO]: EFX ready
17:55:22.011
[17:55:22] [Render thread/INFO]: Sound engine started
17:55:22.011
[17:55:22] [Render thread/INFO]: Sounds reloaded early, because MC sound manager already loaded!
17:55:22.042
[17:55:22] [Render thread/INFO]: emissive suffixes loaded: [_e]
17:55:22.065
[17:55:22] [Render thread/ERROR]: Shutdown failure!
17:55:22.065
java.util.ConcurrentModificationException: null
17:55:22.065
at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
17:55:22.065
at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
17:55:22.065
at net.minecraft.client.texture.TextureManager.close(TextureManager:173) ~[?:?]
17:55:22.065
at net.minecraft.client.MinecraftClient.close(MinecraftClient:1048) ~[?:?]
17:55:22.065
at net.minecraft.client.MinecraftClient.stop(MinecraftClient:1026) ~[?:?]
17:55:22.065
at net.minecraft.client.main.Main.main(Main:252) [client-intermediary.jar:?]
17:55:22.065
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.7.jar:?]
17:55:22.065
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.7.jar:?]
17:55:22.065
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.7.jar:?]
17:55:22.996
Process ended with exit code 0`
Very odd behavior, if you ask me.

**Comment by smellyjoe** [comment]
Disabling "LaunchIntoDestiny" seems to work for me, as for a couple tests do not result in me falling through the world and being consumed by the void. Anyways, thanks for taking the time to assist me with my issue.

**Comment by TheButterbrotMan** [comment]
No problem, i will try to fix this in modpack also

**Comment by TheButterbrotMan** [comment]
https://github.com/Luke100000/minecraft-comes-alive/issues/256
